### ISSUE TITLE
ps: add analyze exclude rule of generated_stories.dart

### ISSUE THREAD

**Issue by Atsumi3** [Atsumi3/storybook_flutter_generator#3]
README.md に generated_stories.dart を analysis_options.yaml で除外追加するように案内する文章の追加

```yaml

analyzer:
  exclude:
    - "**/generated_stories.dart"
```
